# Generated by Django 5.1.5 on 2025-01-29 09:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('borrowing', '0003_review'),
    ]

    operations = [
        migrations.RenameField(
            model_name='review',
            old_name='review',
            new_name='comment',
        ),
    ]
