# Generated by Django 5.1.5 on 2025-01-29 10:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('borrowing', '0004_rename_review_review_comment'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Review',
        ),
    ]
